<a href="https://colab.research.google.com/github/nikamaishwarya319-cmd/Data-Cleaning-nitflix-Dataset/blob/main/Engineering_Feature_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
data = {
    "Name": ["Alex", "Bob", "Charlie", "David", "Ethon"],
    "Age": [22, 26, 35, 40, 35],
    "Salary": [22000, 35000, 45000, 100000, 40000],
    "City": ["Mumbai", "Pune", "Mumbai", "Miraj", "Satara"]
}

df = pd.DataFrame(data)
df

      Name  Age  Salary    City
0     Alex   22   22000  Mumbai
1      Bob   26   35000    Pune
2  Charlie   35   45000  Mumbai
3    David   40  100000   Miraj
4    Ethon   35   40000  Satara

In [11]:
df["Age.Group"]=pd.cut(
df["Age"],
bins=[0,25,40,100],
labels=["Young","Adult","Senior"])
df

      Name  Age  Salary    City Age.Group
0     Alex   22   22000  Mumbai     Young
1      Bob   26   35000    Pune     Adult
2  Charlie   35   45000  Mumbai     Adult
3    David   40  100000   Miraj     Adult
4    Ethon   35   40000  Satara     Adult

In [17]:
def Salary_Categories(Salary):
  if Salary<=35000:
     return"Low"
  elif Salary<=75000:
     return"Medium"
  else:
     return"High"
df["Salary_Calegories"]=df["Salary"].apply(Salary_Categories)
df

      Name  Age  Salary    City Age.Group Salary_Calegories
0     Alex   22   22000  Mumbai     Young               Low
1      Bob   26   35000    Pune     Adult               Low
2  Charlie   35   45000  Mumbai     Adult            Medium
3    David   40  100000   Miraj     Adult              High
4    Ethon   35   40000  Satara     Adult            Medium

In [18]:
City_encoded=pd.get_dummies(df["City"])
City_encoded

   Miraj  Mumbai   Pune  Satara
0  False    True  False   False
1  False   False   True   False
2  False    True  False   False
3   True   False  False   False
4  False   False  False    True

In [19]:
df["Combined"]=df["Salary"]/df["Age"]
df["Combined"]

0    1000.000000
1    1346.153846
2    1285.714286
3    2500.000000
4    1142.857143
Name: Combined, dtype: float64

In [36]:
from sklearn.preprocessing import MinMaxScaler
Scalar=MinMaxScaler()
df["Age_Scaled"]=Scalar.fit_transform(df[["Age"]])
df["Salary_Scaled"]=Scalar.fit_transform(df[["Salary"]])
df

,Name,Age,Salary,City,Age.Group,Salary_Calegories,Combined,Age_Scaled,Salary_Scaled
0,Alex,22,22000,Mumbai,Young,Low,1000.000000,0.000000,0.000000
1,Bob,26,35000,Pune,Adult,Low,1346.153846,0.222222,0.166667
2,Charlie,35,45000,Mumbai,Adult,Medium,1285.714286,0.722222,0.294872
3,David,40,100000,Miraj,Adult,High,2500.000000,1.000000,1.000000
4,Ethon,35,40000,Satara,Adult,Medium,1142.857143,0.722222,0.230769

In [51]:
from sklearn.preprocessing import StandardScaler
Scalar=StandardScaler()
df["Age_Std"]=Scalar.fit_transform(df[["Age"]])
df["Salary_Std"]=Scalar.fit_transform(df[["Salary"]])
df

,Name,Age,Salary,City,Age.Group,Salary_Calegories,Combined,Age_Scaled,Salary_Scaled,Age_Std,Salary_Std
0,Alex,22,22000,Mumbai,Young,Low,1000.000000,0.000000,0.000000,-1.456553,-0.980986
1,Bob,26,35000,Pune,Adult,Low,1346.153846,0.222222,0.166667,-0.849656,-0.497925
2,Charlie,35,45000,Mumbai,Adult,Medium,1285.714286,0.722222,0.294872,0.515863,-0.126339
3,David,40,100000,Miraj,Adult,High,2500.000000,1.000000,1.000000,1.274484,1.917381
4,Ethon,35,40000,Satara,Adult,Medium,1142.857143,0.722222,0.230769,0.515863,-0.312132